---
- name: Autoaccept license
  shell: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections

- name: Add webupd
  apt_repository:
    repo: ppa:webupd8team/java

- name: Install java
  apt:
    name: oracle-java8-installer
    state: latest

- name: Set java
  apt:
    name: oracle-java8-set-default
    state: latest
